---

- name: "deploy play." 
  hosts: k8s
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
      MEMSTASH_TOKEN: "{{ lookup('env', 'MEMSTASH_TOKEN') }}"
  roles:
    - deploy-app
