Description: Backend for Udacity project 5

Parameters:
  ami:
    Description: Ami used for EC2 Instance
    Type: String
    Default: "ami-03d5c68bab01f3496"
  nodeport:
    Description: Nodeport for k8s service
    Type: Number
    Default: 0

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: instanceSG
      GroupDescription: Security group for k8s ec2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref nodeport
          ToPort: !Ref nodeport
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: !Ref ami
      Tags:
        - Key: Name
          Value: EC2 instance udacity project 5
        - Key: project
          Value: udacityProject5
