version: 2.1

orbs:
  slack: circleci/slack@4.4.2

executors:
  node:
    docker:
      - image: circleci/node:13.8.0
  aws:
    docker:
      - image: amazon/aws-cli
  python:
    docker:
      - image: python:3.7-alpine3.11
    
commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      when:
        type: string  
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name udapeople-project-5-backend
          when: << parameters.when >>

jobs:
  create-backend:
    executor: aws
    steps:
      - checkout
      - run:
          name: Create backend
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/k8s.yml \
              --tags project=udacityProject5 \
              --stack-name "udapeople-project-5-backend" 
      - run:
          name: Export ec2 URL to memstash
          command: |
            EC2URL=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicDnsName' \
              --filters "Name=tag:project,Values=udacityProject5" \
              --output text)
            curl -H "Content-Type: text/plain" \
              -H "token: ${MEMSTASH_TOKEN}" \
              --request PUT --data $EC2URL \
              https://api.memstash.io/values/EC2URL-Project-Philipp 
      - destroy-environment:
          when: on_fail

  configure-backend:
    executor: python
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["49:d0:10:4c:a7:87:12:89:ad:bf:6d:42:bf:0c:17:53"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible 
            apk add --update curl
            pip install awscli
      - run:
          name: Add URL to inventory file
          command: |
            URL=$(curl -H "Content-Type: text/plain" \
              -H "token: ${MEMSTASH_TOKEN}" \
              --request GET \
              https://api.memstash.io/values/EC2URL-Project-Philipp) 
            echo $URL >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
      - run:
          name: Configure server
          working_directory: ./.circleci/ansible
          command: |
            cat inventory.txt
            ansible-playbook -vvv -i inventory.txt \
              configure-server.yml 
      - destroy-environment:
          when: on_fail
  
  lint-app:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update make
            apk add --update gcc
            apk add --update musl-dev
      - run:
          name: setup env
          command: |
            make setup
            source ~/.project5/bin/activate
      - run:
          name: installing requirements and linting
          command: |
            make all
  create-and-upload-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: build
          command: |
            docker build --tag=capstone .
            docker image ls
workflows:
  default:
    jobs:
      #- lint-app
      - create-and-upload-docker-image #:
          #requires: [lint-app]
      #- create-backend
      #- configure-backend:
          #requires: [create-backend]