---
- name: Copy capstone.yml to home
  template:
    src: "files/capstone.yml"
    dest: "~/capstone.yml"

- name: Update image tag
  shell: |
    sed -i 's@latest@'"$NEWTAG"'@' capstone.yml

- name: deploy app
  become: yes
  shell: |
    ./kubectl apply -f capstone.yml