apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  strategy:
    type: RollingUpdate
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: phlppsdr/capstone:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  type: NodePort
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000